# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7defd7299d26f133897f742564136d17c6f1fa332258c0b050a2354d097454e426fe8d0dd61f1f13a0c0a0f6a9ad7707ebaba3df9e3533d44a0877049f78320

test:
  secret_key_base: b46f5700924188724ef31a4eeaeb0441b7ae4fad57565f4bb681a5021f676566bf14fde9d8daa2adbf967fb848cff934b3809f1e34605cc80c04b837efab2a0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
